version: '1'
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  blue:
    container_name: blue
    image: gamagochi/blue-green
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Seoul
      - DB_URL=${DB_URL}  # DB_URL을 환경 변수로 사용

  green:
    container_name: green
    image: gamagochi/blue-green
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      - TZ=Asia/Seoul
      - DB_URL=${DB_URL}  # DB_URL을 환경 변수로 사용
