services:
  db:
    image: mysql
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}

  blue:
    container_name: blue
    image: eedoy/gamagochi
    expose:
      - 8080
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}

  green:
    container_name: green
    image: eedoy/gamagochi
    expose:
      - 8080
    ports:
      - 8082:8080
    environment:
      SPRING_DATASOURCE_URL: ${RDS_URL}
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
