spring:
  datasource:
    url: // 개인 URL
    username: // 개인 username
    password:
    driver-class-name: // 개인 Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect  # Use H2Dialect for H2 database
        format_sql: true